# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c94d9d4e8888b654e71f2748ebee9a2bd6edbe337a0e3a56d6bd4adb86c007ad5bd1cb214a87d6920e53858970dcebe0e0d2eefcf24c22326b17dc0a6c9fad25

test:
  secret_key_base: c475373387fad2a3c32c154ce7d1f7dc54cbf3bd5489c240232a0b0ea1a5f24b645b954891d1ce1da46f06324a0807635140db34f56154b040b22734cbc7a1ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
